db:
  image: postgres
  env_file: env/default
  ports:
    - "5432"
app:
  build: ./
  env_file: env/default
  links:
    - db
  command: "honcho run ./run-debug.py"
  ports:
    - "5000:5000"
    - "8000:8000"
  volumes:
    - ".:/app"
